### PR TITLE
Upgrade to Angular 10 and refresh design

### PR DESCRIPTION
**Pull request by berezovskyi**
Angular supports only one major version upgrade at a time. Subsequent PRs will upgrade the project until we reach a supported version of Angular.

As part of the upgrade, I updated the version of ng-bootstrap, and switched most of the styling to use CSS Flex, the "new" CSS layout model which doesn't require many old tricks with floats. New look:

Screen Shot 2022-05-14 at 17 50 13

And in the sample client:

Screen Shot 2022-05-14 at 17 50 42

I think larger padding and removal of extra borders will look better.

I also replaced internal URIs to the SES*** OSLC server with the one towards the OSLC RefImpl, which is openly available.

I envision the notice in the bottom left to be customizable so that the server could render the text like:

> **Requirement** Selection Dialog (**RefImpl RM 2020**; _generated by Eclipse Lyo_)

### CODE REVIEW

**Comment by berezovskyi** [comment]
But I forgot how changes to this repo get pushed to LyoD.

**Comment by jadelkhoury** [comment]
This is how it looks in the resulting generated code. Are the file names of the javascript & stylesheets different? If not, then nothing to change.

https://github.com/OSLC/lyo-adaptor-sample-modelling/blob/main-5.x/adaptor-rm-webapp/src/main/webapp/com/sample/rm/uipreview.jsp

That is, will your changes still produce the same file names under 
https://github.com/OSLC/lyo-adaptor-sample-modelling/tree/main-5.x/adaptor-rm-webapp/src/main/webapp/static/dist/oslc-ui

**Comment by berezovskyi** [comment]
Ok, let’s try to merge this PR and update one of the oslc servers.

**Comment by berezovskyi** [comment]
Do you need any help with this?

**Comment by jadelkhoury** [comment]
I have not given it a go yet really. So, leave it to me for now.

**Review by jadelkhoury — APPROVED** [review]
The generated classes are the same as before, and tested on rm-adaptor. So no changes needed in LyoDesigner.

**Comment by jadelkhoury** [comment]
@berezovskyi I'll just squash and merge so we can close this branch.

**Pull request merged**
